### ISSUE TITLE
Inconsistent routes for encounters with more than 1 word

### ISSUE THREAD

**Issue by Naylepsh** [johnscollins98/react-raid-app#2]
VG route uses snake case ([...]/encounter/w1/vale_guardian) while all the other use kebab case ([...]/encounter/w3/twisted-castle for example). Can we have a more standardized routing?

**Comment by johnscollins98** [comment]
Sure - can add that to list

**Comment by johnscollins98** [comment]
Fixed with commit [7ebc4a4](https://github.com/johnscollins98/react-raid-app/commit/7ebc4a45e24aee1fd07f39a0afcda02b2eb77a1d)
